<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ClInclude Include="$(MSBuildThisFileDirectory)Camera.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)Controller.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)Geometry.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)MapAdapter.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)OpenGLRenderer.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)Presentation.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)Renderer.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)TerrainGeometry.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)TileTexture.h" />
    <ClCompile Include="$(MSBuildThisFileDirectory)Controller.cpp" />
    <ClCompile Include="$(MSBuildThisFileDirectory)MapAdapter.cpp" />
    <ClCompile Include="$(MSBuildThisFileDirectory)OpenGLRenderer.cpp" />
    <ClCompile Include="$(MSBuildThisFileDirectory)Presentation.cpp" />
    <ClCompile Include="$(MSBuildThisFileDirectory)Renderer.cpp" />
    <None Include="$(MSBuildThisFileDirectory)README.md" />
  </ItemGroup>
</Project>
